import axios from 'axios';

const BASE_URL = 'http://localhost:5000/api';

// --- Authentication ---
export async function login(email, password) { return { success: true }; }
export async function signup(name, email, password) { return { success: true }; }
export async function getProfile() { return { name: "User", email: "user@example.com" }; }

// --- Team Information ---
const teamMembers = {
 
  "Team lead & backend and AI": "Mahnoor Fatima",
  "backend helper": "Rana Abdullah",
  "frontend": "Lokesh Kumar",
  "deploy person": "Talha Abid"
};

// --- Helper Functions ---
const addHook = (answer) => `${answer}\n\n*This answer is generated by ORMA's Team AI Memory Assistant. For more details, visit the ORMA dashboard.*`;

// --- Memories Data ---
export async function getMemories() {
  try {
    const res = await axios.get(`${BASE_URL}/memories/all`);
    return res.data.map(m => ({ ...m, id: m._id }));
  } catch (err) {
    return [
      { id: '1', title: 'Getting Started with ORMA', summary: 'ORMA is an intelligent extension to manage user memories.', projectId: 'rag-research' },
      { id: '2', title: 'Hackathon Strategy', summary: 'Focus on core features first to win.', projectId: 'hackathon-ops' },
      { id: '3', title: 'Extension Build Guide', summary: 'How to build a Chrome extension.', projectId: 'extension-build' }
    ];
  }
}

// --- Live Chatbot Logic ---
export async function chatWithMemories(message) {
  const memories = await getMemories();
  const query = message.toLowerCase().trim();
  
  await new Promise(resolve => setTimeout(resolve, 600));

  // 1. Time Awareness Feature
  if (query.includes("date") || query.includes("time")) {
    const now = new Date().toLocaleString();
    return { answer: addHook(`The current date and time is: ${now}. I am always here to assist you!`) };
  }

  // 2. Definition & Full Form
  if (query === "what is orma" || query === "define orma") {
    return { 
      answer: addHook("ORMA stands for 'Organized Retrieval Memory Assistant'. It is a smart memory management extension built by a dedicated team of 4 members to help users organize their knowledge efficiently.") 
    };
  }

  // 3. Logic of ORMA
  if (query === "what is the logic of orma" || query.includes("logic")) {
    return { 
      answer: addHook("ORMA uses RAG (Retrieval-Augmented Generation) logic. It retrieves your saved memory snippets based on your query and uses AI to provide grounded, relevant answers.") 
    };
  }

  // 4. Features/Goal
  if (query.includes("features") || query.includes("what can you do")) {
    return { 
      answer: addHook("I can help you: 1. Search your saved memories. 2. Explain project details. 3. Provide team information. 4. Organize your knowledge base.") 
    };
  }

  // 5. Specific Team Role Queries (Single answer)
  for (const [role, name] of Object.entries(teamMembers)) {
    if (query.includes(role)) {
      return { answer: addHook(`${name.toUpperCase()}`) };
    }
  }

  // 6. General Team Info
  if (query.includes("team") || query.includes("members") || query.includes("who built")) {
    let teamInfo = "### ORMA Chatbot\n\nThe ORMA team consists of:\n";
    Object.entries(teamMembers).forEach(([role, name]) => {
      teamInfo += `- ${role.toUpperCase()}: ${name.toUpperCase()}\n`;
    });
    return { answer: addHook(teamInfo.trim()) };
  }

  // 7. Greetings
  if (["hi", "hello", "hey"].includes(query)) {
    return { answer: addHook("Hello! I am your AI Memory Assistant for ORMA. How can I help you today?") };
  }

  // 8. Memory Search (Contextual)
  const match = memories.find(m => {
    const content = `${m.title} ${m.summary}`.toLowerCase();
    return query.split(' ').some(word => word.length > 3 && content.includes(word));
  });

  if (match) {
    return { answer: addHook(`I found this in your ORMA memories: "${match.title}". Summary: ${match.summary}`) };
  }

  return { answer: addHook("I am here to help! Try asking about 'ORMA', 'Team', 'Logic of ORMA', 'Features', or check the 'Date' and 'Time'.") };
}

// --- Others ---
export async function searchMemories(query) {
  const memories = await getMemories();
  if (!query) return memories;
  return memories.filter(m => m.title?.toLowerCase().includes(query.toLowerCase()));
}

export async function getMemory(id) {
  try {
    const res = await axios.get(`${BASE_URL}/memories/${id}`);
    return { ...res.data, id: res.data._id };
  } catch (err) { return null; }
}

export async function deleteMemory(id) { return { success: true }; }

export async function getProjects() {
  return [
    { id: 'rag-research', name: 'RAG Research', count: 5 },
    { id: 'extension-build', name: 'Extension Build', count: 3 },
    { id: 'hackathon-ops', name: 'Hackathon Ops', count: 2 }
  ];
}